### ISSUE TITLE
Some checks fail when grep is searching for files that do not exist

### ISSUE THREAD

**Issue by criley10** [ansible-lockdown/UBUNTU20-CIS-Audit#7]
Some checks fail because grep attempts to read files that do not exists using a wildcard. This is a very minor bug, but could be confusing to some users when a redediation is implemented, but the audit fails.

From "**1.5.4 | L1 | Ensure core dumps are restricted | security/limits.conf**" :

```
root@server:~# grep -E "\*.*hard.*core.*0" /etc/security/limits.conf /etc/security/limits.d/*
/etc/security/limits.conf:* hard core 0
grep: /etc/security/limits.d/*: No such file or directory
```
This results in  a exit code of 2 and results in a failed test.

**Expected Behavior**
The tasks should only check these files if they exist.

**Actual Behavior**
Some checks fail when the control is in place.

**Control(s) Affected**
This issue could effect any check where a wildcard is used with grep. 

Files that may match this pattern based on a quick search:
[section_1/cis_1.3/cis_1.3.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_1/cis_1.3/cis_1.3.2.yml)
[section_1/cis_1.5/cis_1.5.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_1/cis_1.5/cis_1.5.2.yml)
[section_1/cis_1.5/cis_1.5.4.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_1/cis_1.5/cis_1.5.4.yml)
[section_1/cis_1.7/cis_1.7.1.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_1/cis_1.7/cis_1.7.1.yml)
[section_3/cis_3.2/cis_3.2.1.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.2/cis_3.2.1.yml)
[section_3/cis_3.2/cis_3.2.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.2/cis_3.2.2.yml)
[section_3/cis_3.3/cis_3.3.1.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.1.yml)
[section_3/cis_3.3/cis_3.3.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.2.yml)
[section_3/cis_3.3/cis_3.3.3.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.3.yml)
[section_3/cis_3.3/cis_3.3.4.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.4.yml)
[section_3/cis_3.3/cis_3.3.5.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.5.yml)
[section_3/cis_3.3/cis_3.3.6.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.6.yml)
[section_3/cis_3.3/cis_3.3.7.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.7.yml)
[section_3/cis_3.3/cis_3.3.8.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/cis_3.3.8.yml)
[section_3/cis_3.3/ipv6/cis_3.3.1.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/ipv6/cis_3.3.1.yml)
[section_3/cis_3.3/ipv6/cis_3.3.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/ipv6/cis_3.3.2.yml)
[section_3/cis_3.3/ipv6/cis_3.3.9.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_3/cis_3.3/ipv6/cis_3.3.9.yml)
[section_4/cis_4.1/cis_4.1.3.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.3.yml)
[section_4/cis_4.1/cis_4.1.4.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.4.yml)
[section_4/cis_4.1/cis_4.1.5.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.5.yml)
[section_4/cis_4.1/cis_4.1.6.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.6.yml)
[section_4/cis_4.1/cis_4.1.7.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.7.yml)
[section_4/cis_4.1/cis_4.1.8.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.8.yml)
[section_4/cis_4.1/cis_4.1.9.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.9.yml)
[section_4/cis_4.1/cis_4.1.10.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.10.yml)
[section_4/cis_4.1/cis_4.1.11.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.11.yml)
[section_4/cis_4.1/cis_4.1.12.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.12.yml)
[section_4/cis_4.1/cis_4.1.13.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.13.yml)
[section_4/cis_4.1/cis_4.1.14.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.14.yml)
[section_4/cis_4.1/cis_4.1.15.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.15.yml)
[section_4/cis_4.1/cis_4.1.16.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.16.yml)
[section_4/cis_4.1/cis_4.1.17.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.1/cis_4.1.17.yml)
[section_4/cis_4.2/cis_4.2.1.4.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.2/cis_4.2.1.4.yml)
[section_4/cis_4.2/cis_4.2.1.5.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.2/cis_4.2.1.5.yml)
[section_4/cis_4.2/cis_4.2.1.6.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.2/cis_4.2.1.6.yml)
[section_4/cis_4.4/cis_4.4.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_4/cis_4.4/cis_4.4.yml)
[section_5/cis_5.2/cis_5.2.2.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_5/cis_5.2/cis_5.2.2.yml)
[section_5/cis_5.2/cis_5.2.3.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_5/cis_5.2/cis_5.2.3.yml)
[section_5/cis_5.3/cis_5.3.18.yml](https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit/blob/devel/section_5/cis_5.3/cis_5.3.18.yml)

**Environment (please complete the following information):**

- goss version: `goss version v0.3.16`
- OS version: `Ubuntu 20.04.4 LTS`
- Additional Details:

**Additional Notes**

**Possible Solution**
Something like this may work to get a list of non-empty files and add them to the grep command without ifs:
```
root@server:~# files=$(shopt -s nullglob dotglob; echo /etc/security/limits.d/*) && grep -E "\*.*hard.*core.*0" /etc/security/limits.conf $files
* hard core 0
root@server:~# echo $?
0
```

**Comment by uk-bolly** [comment]
hi @criley10 

Thank you for your feedback, apologies for not responding sooner. There has recently been a rewrite of alot of rules for Ubuntu (devel branch). I believe this issue has been addressed. You should see a big increase in the number of tests that actually take place also.

Please let us know if this works for you?

Many thanks

uk-bolly
